!!top.datadriven.raft.core.model.config.ConfigModel
localNode: {ip: localhost, port: 20881, serverId: 1}
remoteNodes:
  - {ip: localhost, port: 20882, serverId: 2}
  - {ip: localhost, port: 20883, serverId: 3}
  - {ip: localhost, port: 20884, serverId: 4}
  - {ip: localhost, port: 20885, serverId: 5}